# Generated by vmake version 10.4b

# Define path to each library
LIB_WORK = per_pwm_lib
LIB_STD = /opt/altera/15.1/modelsim_ase/linuxaloem/../std
LIB_IEEE = /opt/altera/15.1/modelsim_ase/linuxaloem/../ieee
LIB_PER_PWM_LIB = per_pwm_lib

# Define path to each design unit
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
IEEE__numeric_std = $(LIB_IEEE)/_lib.qdb
PER_PWM_LIB__pwm_pkg = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__pwm__rtl = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__pwm = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_pwm_tb__testbench = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_pwm_tb = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_pwm_pkg = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_pwm__rtl = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_pwm = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_iface_pkg = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_iface__rtl = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__per_iface = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__log2_pkg__body = $(LIB_PER_PWM_LIB)/_lib.qdb
PER_PWM_LIB__log2_pkg = $(LIB_PER_PWM_LIB)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_PER_PWM_LIB)/_lib.qdb

$(LIB_PER_PWM_LIB)/_lib.qdb : ../../../src/packages/math/log2_pkg.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/packages/math/body/log2_pkg-body.vhd \
		$(PER_PWM_LIB__log2_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_iface/rtl/per_iface_entity.vhd \
		$(PER_PWM_LIB__per_iface_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_iface/rtl/per_iface_arch.vhd \
		$(PER_PWM_LIB__per_iface_pkg) \
		$(PER_PWM_LIB__per_iface) \
		$(PER_PWM_LIB__log2_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_iface/rtl/per_iface_pkg.vhd \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_entity.vhd \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_arch.vhd \
		$(PER_PWM_LIB__per_pwm) \
		$(PER_PWM_LIB__pwm_pkg) \
		$(PER_PWM_LIB__per_iface_pkg) \
		$(PER_PWM_LIB__per_pwm_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_pkg.vhd \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_tb.vhd \
		$(PER_PWM_LIB__per_pwm_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/pwm_entity.vhd \
		$(PER_PWM_LIB__pwm_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/pwm_arch.vhd \
		$(PER_PWM_LIB__pwm_pkg) \
		$(PER_PWM_LIB__pwm) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/per_pwm/rtl/pwm_pkg.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164)
	$(VCOM) -work per_pwm_lib -2008 ../../../src/packages/math/log2_pkg.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/packages/math/body/log2_pkg-body.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_iface/rtl/per_iface_pkg.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_iface/rtl/per_iface_entity.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_iface/rtl/per_iface_arch.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/pwm_pkg.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/pwm_entity.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/pwm_arch.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_pkg.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_entity.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_arch.vhd
	$(VCOM) -work per_pwm_lib -2008 ../../../src/omsp_peripherals/per_pwm/rtl/per_pwm_tb.vhd

