# Generated by vmake version 10.4b

# Define path to each library
LIB_STD = /opt/altera/15.1/modelsim_ase/linuxaloem/../std
LIB_IEEE = /opt/altera/15.1/modelsim_ase/linuxaloem/../ieee
LIB_WORK = ram16_lib
LIB_RAM16_LIB = ram16_lib

# Define path to each design unit
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
IEEE__numeric_std = $(LIB_IEEE)/_lib.qdb
RAM16_LIB__ram16_tb__test_bench = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__ram16_tb = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__ram16_pkg = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__ram16__rtl = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__ram16 = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__log2_pkg__body = $(LIB_RAM16_LIB)/_lib.qdb
RAM16_LIB__log2_pkg = $(LIB_RAM16_LIB)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_RAM16_LIB)/_lib.qdb

$(LIB_RAM16_LIB)/_lib.qdb : ../../../src/packages/math/log2_pkg.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/packages/math/body/log2_pkg-body.vhd \
		$(RAM16_LIB__log2_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/ram16/rtl/ram16_entity.vhd \
		$(IEEE__numeric_std) \
		$(RAM16_LIB__log2_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/ram16/rtl/ram16_arch.vhd \
		$(RAM16_LIB__ram16) \
		$(RAM16_LIB__log2_pkg) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/ram16/rtl/ram16_pkg.vhd \
		$(IEEE__numeric_std) \
		$(RAM16_LIB__log2_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) ../../../src/omsp_peripherals/ram16/rtl/ram16_tb.vhd \
		$(RAM16_LIB__ram16_pkg) \
		$(IEEE__numeric_std) \
		$(RAM16_LIB__log2_pkg) \
		$(STD__textio) \
		$(IEEE__std_logic_1164)
	$(VCOM) -work ram16_lib -2008 ../../../src/packages/math/log2_pkg.vhd
	$(VCOM) -work ram16_lib -2008 ../../../src/packages/math/body/log2_pkg-body.vhd
	$(VCOM) -work ram16_lib -2008 ../../../src/omsp_peripherals/ram16/rtl/ram16_entity.vhd
	$(VCOM) -work ram16_lib -2008 ../../../src/omsp_peripherals/ram16/rtl/ram16_arch.vhd
	$(VCOM) -work ram16_lib -2008 ../../../src/omsp_peripherals/ram16/rtl/ram16_pkg.vhd
	$(VCOM) -work ram16_lib -2008 ../../../src/omsp_peripherals/ram16/rtl/ram16_tb.vhd

